[package]
name = "temporal-logic"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "5da3eb031bbd567178c0bda04281b78605a351e0"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "d0d1b62ed439f7bd83b647acc2ac392b01ddcd71"}
