[package]
name = "temporal-logic"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "93380c19b9cf775b8c97805e4b5c61ec6748b556"}
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "03fefd43615ffcd59ed39bb08a891bc76f65b07b"}
