[package]
name = "temporal-logic"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "f7977ff5a6bcf7e5c54eec908364ceb40dafc795"}
lean-lib = {git = "https://github.com/unitb/lean-lib", rev = "f306e35ef3ef579f0ac615927aed7b80cb4375f0"}
